//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_CKd8oXXYEeimL6JFnA2zmA,_3dAZwXXqEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Definir Requisitos_3E5BF9DC_8679023e_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_CKd8oXXYEeimL6JFnA2zmA,_3dAZwXXqEeimL6JFnA2zmAActivityDetail"]="./../../processoportal/deliveryprocesses/resources/Definir Requisitos_3E5BF9DC_8679023e_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_PLp8MXXyEeimL6JFnA2zmA,_qC8uwXXyEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Resultados Tetes_8E2A9EC9_23bd6535_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_PLp8MXXyEeimL6JFnA2zmA,_qC8uwXXyEeimL6JFnA2zmAActivityDetail"]="./../../processoportal/deliveryprocesses/resources/Resultados Tetes_8E2A9EC9_23bd6535_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_8U9jAXXxEeimL6JFnA2zmA,_En4bcXXyEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Agregar Artes Funcionalidades_4F4D82E5_b58f6286_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_8U9jAXXxEeimL6JFnA2zmA,_En4bcXXyEeimL6JFnA2zmAActivityDetail"]="./../../processoportal/deliveryprocesses/resources/Agregar Artes Funcionalidades_4F4D82E5_b58f6286_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_PfakgXXYEeimL6JFnA2zmA,_5YuDEXXrEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Dialogo com Gerentes_166D4778_40ab2fe6_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_PfakgXXYEeimL6JFnA2zmA,_5YuDEXXrEeimL6JFnA2zmAActivityDetail"]="./../../processoportal/deliveryprocesses/resources/Dialogo com Gerentes_166D4778_40ab2fe6_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_CKd8oXXYEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Levantar Requisitos_3525F67E_28c0440e_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/processoPortalDiagrama_A62CB33C_a62cb33c_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_QauWMXXYEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Implementacao_D39C4ED6_c7369c66_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_qkr38XX0EeimL6JFnA2zmA,_s_NZoXX0EeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Implantar_6EC0AD71_c5320ee0_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_qkr38XX0EeimL6JFnA2zmA,_s_NZoXX0EeimL6JFnA2zmAActivityDetail"]="./../../processoportal/deliveryprocesses/resources/Implantar_6EC0AD71_c5320ee0_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_PLp8MXXyEeimL6JFnA2zmA,_nrQeoXXyEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Receber Sistema_EA4743DA_7fda0a46_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_PLp8MXXyEeimL6JFnA2zmA,_nrQeoXXyEeimL6JFnA2zmAActivityDetail"]="./../../processoportal/deliveryprocesses/resources/Receber Sistema_EA4743DA_7fda0a46_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_SJOKQXXWEeimL6JFnA2zmA,_XeX_IXXYEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Idealizar_D15E7BFC_acec0731_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_SJOKQXXWEeimL6JFnA2zmA,_XeX_IXXYEeimL6JFnA2zmAActivityDetail"]="./../../processoportal/deliveryprocesses/resources/Idealizar_D15E7BFC_acec0731_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_8U9jAXXxEeimL6JFnA2zmA,_-FBLYXXxEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/d_B184BAFA_17c69a9b_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_8U9jAXXxEeimL6JFnA2zmA,_-FBLYXXxEeimL6JFnA2zmAActivityDetail"]="./../../processoportal/deliveryprocesses/resources/d_B184BAFA_17c69a9b_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_PLp8MXXyEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Teste_122CB288_5c70018_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_Tz8rEXX0EeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Alteracoes Pos Testes_98D29DA3_8c6ceb33_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_PLp8MXXyEeimL6JFnA2zmA,_V3BA8XXyEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Testes_7A5076D5_fe33d41_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_PLp8MXXyEeimL6JFnA2zmA,_V3BA8XXyEeimL6JFnA2zmAActivityDetail"]="./../../processoportal/deliveryprocesses/resources/Testes_7A5076D5_fe33d41_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_Tz8rEXX0EeimL6JFnA2zmA,_XnSZ0XX0EeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Receber Portal_21DEEB75_26debbfc_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_Tz8rEXX0EeimL6JFnA2zmA,_XnSZ0XX0EeimL6JFnA2zmAActivityDetail"]="./../../processoportal/deliveryprocesses/resources/Receber Portal_21DEEB75_26debbfc_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_8U9jAXXxEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Agregacao_BDD3DABD_b16e284d_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_QauWMXXYEeimL6JFnA2zmA,_6SvwcXXtEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Desenvolver Funcionalidades_EEBFE507_5e65bdc1_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_QauWMXXYEeimL6JFnA2zmA,_6SvwcXXtEeimL6JFnA2zmAActivityDetail"]="./../../processoportal/deliveryprocesses/resources/Desenvolver Funcionalidades_EEBFE507_5e65bdc1_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_8U9jAXXxEeimL6JFnA2zmA,_J3wZoXXyEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Verificar Agregacao_7188398E_d7ca192f_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_8U9jAXXxEeimL6JFnA2zmA,_J3wZoXXyEeimL6JFnA2zmAActivityDetail"]="./../../processoportal/deliveryprocesses/resources/Verificar Agregacao_7188398E_d7ca192f_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_Tz8rEXX0EeimL6JFnA2zmA,_eSDosXX0EeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Corrigir e Atualizar_6134244E_6633f4d5_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_Tz8rEXX0EeimL6JFnA2zmA,_eSDosXX0EeimL6JFnA2zmAActivityDetail"]="./../../processoportal/deliveryprocesses/resources/Corrigir e Atualizar_6134244E_6633f4d5_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_QauWMXXYEeimL6JFnA2zmA,_xqouUXXxEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Criar Artes_CDD8725A_3d7e4b14_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_QauWMXXYEeimL6JFnA2zmA,_xqouUXXxEeimL6JFnA2zmAActivityDetail"]="./../../processoportal/deliveryprocesses/resources/Criar Artes_CDD8725A_3d7e4b14_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_qkr38XX0EeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Implantacao_FB56668B_eef0b41b_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_CKd8oXXYEeimL6JFnA2zmA,_KBRThXfKEei1LJy4i5tyEQActivity"]="./../../processoportal/deliveryprocesses/resources/Validar Requisitos_3A04682B_8221708d_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_CKd8oXXYEeimL6JFnA2zmA,_KBRThXfKEei1LJy4i5tyEQActivityDetail"]="./../../processoportal/deliveryprocesses/resources/Validar Requisitos_3A04682B_8221708d_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_SJOKQXXWEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Concepcao_17780251_b124fe1_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_PfakgXXYEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Projeto_7B8F3A8A_6f29881a_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_PLp8MXXyEeimL6JFnA2zmA,_Bra04XXzEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Resultado_produto_BD5EA69D_52f16d09_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_PLp8MXXyEeimL6JFnA2zmA,_Bra04XXzEeimL6JFnA2zmAActivityDetail"]="./../../processoportal/deliveryprocesses/resources/Resultado_produto_BD5EA69D_52f16d09_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_SJOKQXXWEeimL6JFnA2zmA,_n0SdoXXYEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Especificar_7103FB75_4c9186aa_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_SJOKQXXWEeimL6JFnA2zmA,_n0SdoXXYEeimL6JFnA2zmAActivityDetail"]="./../../processoportal/deliveryprocesses/resources/Especificar_7103FB75_4c9186aa_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_SJOKQXXWEeimL6JFnA2zmA,_vNnJsXXaEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Requerer_8B051E7A_6692a9af_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_SJOKQXXWEeimL6JFnA2zmA,_vNnJsXXaEeimL6JFnA2zmAActivityDetail"]="./../../processoportal/deliveryprocesses/resources/Requerer_8B051E7A_6692a9af_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_PfakgXXYEeimL6JFnA2zmA,__LfdgXXsEeimL6JFnA2zmAActivity"]="./../../processoportal/deliveryprocesses/resources/Dialogar com Equipes_1CA588EF_46e3715d_Activity.jpeg"
contentPage.processPage.imageFiles["_X80McXXJEeimL6JFnA2zmA,_PfakgXXYEeimL6JFnA2zmA,__LfdgXXsEeimL6JFnA2zmAActivityDetail"]="./../../processoportal/deliveryprocesses/resources/Dialogar com Equipes_1CA588EF_46e3715d_ActivityDetail.jpeg"
contentPage.processPage.elementUrls["_D5F1FHXtEeimL6JFnA2zmA"] = ["gerente_portal","processoportal/deliveryprocesses/gerente_portal_D60FEA72.html"];
contentPage.processPage.elementUrls["_KBRTg3fKEei1LJy4i5tyEQ"] = ["resultado_analise","processoportal/deliveryprocesses/resultado_analise_CCE56FE7.html"];
contentPage.processPage.elementUrls["_3dAZwXXqEeimL6JFnA2zmA"] = ["Definir Requisitos","processoportal/deliveryprocesses/Definir Requisitos_3E5BF9DC.html"];
contentPage.processPage.elementUrls["_6SvwcXXtEeimL6JFnA2zmA"] = ["Desenvolver Funcionalidades","processoportal/deliveryprocesses/Desenvolver Funcionalidades_EEBFE507.html"];
contentPage.processPage.elementUrls["_Tz8rEXX0EeimL6JFnA2zmA"] = ["Alteracoes Pos Testes","processoportal/deliveryprocesses/Alteracoes Pos Testes_98D29DA3.html"];
contentPage.processPage.elementUrls["_zasWsHXxEeimL6JFnA2zmA"] = ["objeto_requerido","processoportal/deliveryprocesses/objeto_requerido_945F13F8.html"];
contentPage.processPage.elementUrls["_x0REEHX0EeimL6JFnA2zmA"] = ["devops","processoportal/deliveryprocesses/devops_34489B5E.html"];
contentPage.processPage.elementUrls["_vNnJsXXaEeimL6JFnA2zmA"] = ["Requerer","processoportal/deliveryprocesses/Requerer_8B051E7A.html"];
contentPage.processPage.elementUrls["_FgBzIHXsEeimL6JFnA2zmA"] = ["explanacao_portal","processoportal/deliveryprocesses/explanacao_portal_53E4158B.html"];
contentPage.processPage.elementUrls["_kBR8snXxEeimL6JFnA2zmA"] = ["funcionalidades_desenvolvidas","processoportal/deliveryprocesses/funcionalidades_desenvolvidas_61BBE590.html"];
contentPage.processPage.elementUrls["_ZuBGhXXYEeimL6JFnA2zmA"] = ["ideia_portal","processoportal/deliveryprocesses/ideia_portal_45C214C9.html"];
contentPage.processPage.elementUrls["_qMuUoHXYEeimL6JFnA2zmA"] = ["explanar_necessidade","processoportal/deliveryprocesses/explanar_necessidade_1DCDD92E.html"];
contentPage.processPage.elementUrls["_SJOKQXXWEeimL6JFnA2zmA"] = ["Concepcao","processoportal/deliveryprocesses/Concepcao_17780251.html"];
contentPage.processPage.elementUrls["_qxOv4HXYEeimL6JFnA2zmA"] = ["questionar","processoportal/deliveryprocesses/questionar_ED0C07B.html"];
contentPage.processPage.elementUrls["_KBRThXfKEei1LJy4i5tyEQ"] = ["Validar Requisitos","processoportal/deliveryprocesses/Validar Requisitos_3A04682B.html"];
contentPage.processPage.elementUrls["_AxdHBHXzEeimL6JFnA2zmA"] = ["usabilidade","processoportal/deliveryprocesses/usabilidade_36A9D7DB.html"];
contentPage.processPage.elementUrls["_W1TOIHXyEeimL6JFnA2zmA"] = ["testar_funcionalidades","processoportal/deliveryprocesses/testar_funcionalidades_7368D5AD.html"];
contentPage.processPage.elementUrls["_kA1QwHXxEeimL6JFnA2zmA"] = ["desenvolvedores_portal","processoportal/deliveryprocesses/desenvolvedores_portal_A7FA6DFF.html"];
contentPage.processPage.elementUrls["_5PvisHXqEeimL6JFnA2zmA"] = ["definir_requisitos","processoportal/deliveryprocesses/definir_requisitos_340BF474.html"];
contentPage.processPage.elementUrls["_G010gnXtEeimL6JFnA2zmA"] = ["estimar_prazo_arte","processoportal/deliveryprocesses/estimar_prazo_arte_ACB87163.html"];
contentPage.processPage.elementUrls["_Bra04XXzEeimL6JFnA2zmA"] = ["Produto Pos Testes","processoportal/deliveryprocesses/Resultado_produto_BD5EA69D.html"];
contentPage.processPage.elementUrls["_IhB3QnXyEeimL6JFnA2zmA"] = ["uniao_arte_funcionalidade","processoportal/deliveryprocesses/uniao_arte_funcionalidade_22B7A106.html"];
contentPage.processPage.elementUrls["_D48EEHXtEeimL6JFnA2zmA"] = ["explanar_prototipo","processoportal/deliveryprocesses/explanar_prototipo_6B5AFCB4.html"];
contentPage.processPage.elementUrls["_xqouUXXxEeimL6JFnA2zmA"] = ["Criar Artes","processoportal/deliveryprocesses/Criar Artes_CDD8725A.html"];
contentPage.processPage.elementUrls["_GsBFIHXsEeimL6JFnA2zmA"] = ["prototipar_portal","processoportal/deliveryprocesses/prototipar_portal_AAF97702.html"];
contentPage.processPage.elementUrls["_Mj3aknXyEeimL6JFnA2zmA"] = ["desenvolvedores_portal","processoportal/deliveryprocesses/desenvolvedores_portal_AEF36EC7.html"];
contentPage.processPage.elementUrls["_GJJooHXsEeimL6JFnA2zmA"] = ["mostrar_requisitos","processoportal/deliveryprocesses/mostrar_requisitos_17A10D4.html"];
contentPage.processPage.elementUrls["_OzPmxHXzEeimL6JFnA2zmA"] = ["sistema_testado","processoportal/deliveryprocesses/sistema_testado_C2ED0B92.html"];
contentPage.processPage.elementUrls["_9I_ykHXyEeimL6JFnA2zmA"] = ["receber_sistema","processoportal/deliveryprocesses/receber_sistema_AB5C4300.html"];
contentPage.processPage.elementUrls["_W15rEHXyEeimL6JFnA2zmA"] = ["sistema_validado","processoportal/deliveryprocesses/sistema_validado_72D3B513.html"];
contentPage.processPage.elementUrls["_AxJlAHXzEeimL6JFnA2zmA"] = ["equipe_teste","processoportal/deliveryprocesses/equipe_teste_D79DEF3A.html"];
contentPage.processPage.elementUrls["_5YuDEXXrEeimL6JFnA2zmA"] = ["Elaborar Solucao","processoportal/deliveryprocesses/Dialogo com Gerentes_166D4778.html"];
contentPage.processPage.elementUrls["_GUzpkHXtEeimL6JFnA2zmA"] = ["dividir_tarefas_desenvolvimento","processoportal/deliveryprocesses/dividir_tarefas_desenvolvimento_FA312B5.html"];
contentPage.processPage.elementUrls["_FqL_QnXtEeimL6JFnA2zmA"] = ["arte_finalizada","processoportal/deliveryprocesses/arte_finalizada_A4D92C4F.html"];
contentPage.processPage.elementUrls["_Ff4CJnXsEeimL6JFnA2zmA"] = ["gerente_teste","processoportal/deliveryprocesses/gerente_teste_2A9F3CA6.html"];
contentPage.processPage.elementUrls["_wy8IxHXaEeimL6JFnA2zmA"] = ["abrir_protocolo","processoportal/deliveryprocesses/solicitar_protocolo_51AA0684.html"];
contentPage.processPage.elementUrls["_AxdHAnXzEeimL6JFnA2zmA"] = ["interacao","processoportal/deliveryprocesses/interacao_6B4EE9E2.html"];
contentPage.processPage.elementUrls["_ZuBGgHXYEeimL6JFnA2zmA"] = ["idealizar_portal","processoportal/deliveryprocesses/idealizar_portal_7692529A.html"];
contentPage.processPage.elementUrls["_QauWMXXYEeimL6JFnA2zmA"] = ["Implementacao","processoportal/deliveryprocesses/Implementacao_D39C4ED6.html"];
contentPage.processPage.elementUrls["_G0ZIkHXtEeimL6JFnA2zmA"] = ["estimar_prazo_artes","processoportal/deliveryprocesses/estimar_prazo_artes_F457E6C9.html"];
contentPage.processPage.elementUrls["_GJJoonXsEeimL6JFnA2zmA"] = ["compreender_requisitos","processoportal/deliveryprocesses/compreender_requisitos_FAB104FA.html"];
contentPage.processPage.elementUrls["_wy8IwHXaEeimL6JFnA2zmA"] = ["idealizador","processoportal/deliveryprocesses/idealizador_8D182465.html"];
contentPage.processPage.elementUrls["_ZctDUHX0EeimL6JFnA2zmA"] = ["receber_portal","processoportal/deliveryprocesses/receber_portal_3207DE3C.html"];
contentPage.processPage.elementUrls["_D5F1FnXtEeimL6JFnA2zmA"] = ["gerente_arte","processoportal/deliveryprocesses/gerente_arte_CF46DE98.html"];
contentPage.processPage.elementUrls["_qkr38XX0EeimL6JFnA2zmA"] = ["Implantacao","processoportal/deliveryprocesses/Implantacao_FB56668B.html"];
contentPage.processPage.elementUrls["_5QCdoHXqEeimL6JFnA2zmA"] = ["idealizador","processoportal/deliveryprocesses/idealizador_4CBC3C7.html"];
contentPage.processPage.elementUrls["_x0j_AHX0EeimL6JFnA2zmA"] = ["produto_final","processoportal/deliveryprocesses/produto_final_BC7B1964.html"];
contentPage.processPage.elementUrls["_DW-NMHXyEeimL6JFnA2zmA"] = ["desenvolvedores_portal","processoportal/deliveryprocesses/desenvolvedores_portal_5125EB48.html"];
contentPage.processPage.elementUrls["_NHLjAHXyEeimL6JFnA2zmA"] = ["recebe_sistema","processoportal/deliveryprocesses/recebe_sistema_29CDE018.html"];
contentPage.processPage.elementUrls["_qMbZsHXYEeimL6JFnA2zmA"] = ["entender_problema","processoportal/deliveryprocesses/entender_problema_3666162.html"];
contentPage.processPage.elementUrls["_NHLjAnXyEeimL6JFnA2zmA"] = ["sistema_validado","processoportal/deliveryprocesses/sistema_validado_2304D43E.html"];
contentPage.processPage.elementUrls["_NG4oEHXyEeimL6JFnA2zmA"] = ["gerente_arte","processoportal/deliveryprocesses/gerente_arte_7CA442F0.html"];
contentPage.processPage.elementUrls["_n0SdoXXYEeimL6JFnA2zmA"] = ["Especificar","processoportal/deliveryprocesses/Especificar_7103FB75.html"];
contentPage.processPage.elementUrls["_FflHMHXsEeimL6JFnA2zmA"] = ["apresentar_ideia_portal","processoportal/deliveryprocesses/apresentar_ideia_portal_2ED8BC6A.html"];
contentPage.processPage.elementUrls["_DXRIIHXyEeimL6JFnA2zmA"] = ["funcionalidades_separadas","processoportal/deliveryprocesses/funcionalidades_separadas_C1876B43.html"];
contentPage.processPage.elementUrls["_f0jWMnX0EeimL6JFnA2zmA"] = ["gerente_portal","processoportal/deliveryprocesses/gerente_portal_9CE79C8.html"];
contentPage.processPage.elementUrls["_kBR8sHXxEeimL6JFnA2zmA"] = ["objeto_requerido","processoportal/deliveryprocesses/objeto_requerido_6884F16A.html"];
contentPage.processPage.elementUrls["_f1ACIHX0EeimL6JFnA2zmA"] = ["sistema_testado","processoportal/deliveryprocesses/sistema_testado_E0ADFA5C.html"];
contentPage.processPage.elementUrls["_qMuUonXYEeimL6JFnA2zmA"] = ["necessidade_existente","processoportal/deliveryprocesses/necessidade_existente_1704CD54.html"];
contentPage.processPage.elementUrls["_IhB3QHXyEeimL6JFnA2zmA"] = ["partes_separadas","processoportal/deliveryprocesses/partes_separadas_2980ACE0.html"];
contentPage.processPage.elementUrls["_J3wZoXXyEeimL6JFnA2zmA"] = ["Verificar Agregacao","processoportal/deliveryprocesses/Verificar Agregacao_7188398E.html"];
contentPage.processPage.elementUrls["_wy8IwnXaEeimL6JFnA2zmA"] = ["diretor","processoportal/deliveryprocesses/diretor_864F188B.html"];
contentPage.processPage.elementUrls["_Mj3akHXyEeimL6JFnA2zmA"] = ["componentes_arte","processoportal/deliveryprocesses/componentes_arte_B5BC7AA1.html"];
contentPage.processPage.elementUrls["_CKd8oXXYEeimL6JFnA2zmA"] = ["Requisitos","processoportal/deliveryprocesses/Levantar Requisitos_3525F67E.html"];
contentPage.processPage.elementUrls["_f0GqQHX0EeimL6JFnA2zmA"] = ["correcoes_atualizacao","processoportal/deliveryprocesses/correcoes_atualizacao_5B0CACBB.html"];
contentPage.processPage.elementUrls["_HVLhcnXtEeimL6JFnA2zmA"] = ["sistema_finalizado","processoportal/deliveryprocesses/sistema_finalizado_6B0212E9.html"];
contentPage.processPage.elementUrls["_x0j_AnX0EeimL6JFnA2zmA"] = ["portal_publicado","processoportal/deliveryprocesses/portal_publicado_B5B20D8A.html"];
contentPage.processPage.elementUrls["_En4bcXXyEeimL6JFnA2zmA"] = ["Agregar Artes + Funcionalidades","processoportal/deliveryprocesses/Agregar Artes Funcionalidades_4F4D82E5.html"];
contentPage.processPage.elementUrls["_DXRIInXyEeimL6JFnA2zmA"] = ["unir_funcionalidades","processoportal/deliveryprocesses/unir_funcionalidades_BABE5F69.html"];
contentPage.processPage.elementUrls["_s_NZoXX0EeimL6JFnA2zmA"] = ["Implantar ","processoportal/deliveryprocesses/Implantar_6EC0AD71.html"];
contentPage.processPage.elementUrls["_Aws5EHXzEeimL6JFnA2zmA"] = ["retorno_teste","processoportal/deliveryprocesses/retorno_teste_C69CD6F5.html"];
contentPage.processPage.elementUrls["_Oyy60HXzEeimL6JFnA2zmA"] = ["devolver_sistema","processoportal/deliveryprocesses/devolver_sistema_569CD219.html"];
contentPage.processPage.elementUrls["_qMlKsnXYEeimL6JFnA2zmA"] = ["diretor","processoportal/deliveryprocesses/diretor_FBF3FAEF.html"];
contentPage.processPage.elementUrls["_D5YwAHXtEeimL6JFnA2zmA"] = ["mostrar_prototipo","processoportal/deliveryprocesses/mostrar_prototipo_6CD023AA.html"];
contentPage.processPage.elementUrls["_NGltIHXyEeimL6JFnA2zmA"] = ["validar_agregacao","processoportal/deliveryprocesses/validar_agregacao_3EA698F9.html"];
contentPage.processPage.elementUrls["_ZctDVXX0EeimL6JFnA2zmA"] = ["sistema_testado","processoportal/deliveryprocesses/sistema_testado_137A06B.html"];
contentPage.processPage.elementUrls["_xz0YIHX0EeimL6JFnA2zmA"] = ["subir_sistema","processoportal/deliveryprocesses/subir_sistema_3898459A.html"];
contentPage.processPage.elementUrls["_D5F1EnXtEeimL6JFnA2zmA"] = ["componentes_arte","processoportal/deliveryprocesses/componentes_arte_AB4FC79.html"];
contentPage.processPage.elementUrls["_zasWsnXxEeimL6JFnA2zmA"] = ["artes_criadas","processoportal/deliveryprocesses/artes_criadas_8D96081E.html"];
contentPage.processPage.elementUrls["_GsUnInXsEeimL6JFnA2zmA"] = ["prototipo_finalizado","processoportal/deliveryprocesses/prototipo_finalizado_F7D29A5D.html"];
contentPage.processPage.elementUrls["_AxJlAnXzEeimL6JFnA2zmA"] = ["gerente_teste","processoportal/deliveryprocesses/gerente_teste_D0D4E360.html"];
contentPage.processPage.elementUrls["_G010gHXtEeimL6JFnA2zmA"] = ["especificar_dificuldade","processoportal/deliveryprocesses/especificar_dificuldade_arte_B3817D3D.html"];
contentPage.processPage.elementUrls["_D5YwAnXtEeimL6JFnA2zmA"] = ["compreender_projeto","processoportal/deliveryprocesses/compreender_projeto_660717D0.html"];
contentPage.processPage.elementUrls["_HVLhcHXtEeimL6JFnA2zmA"] = ["estimar_prazo_desenvolvimento","processoportal/deliveryprocesses/estimar_prazo_desenvolvimento_71CB1EC3.html"];
contentPage.processPage.elementUrls["_qxiR4HXYEeimL6JFnA2zmA"] = ["problema","processoportal/deliveryprocesses/problema_A94AC6FD.html"];
contentPage.processPage.elementUrls["_qMlKtHXYEeimL6JFnA2zmA"] = ["gerente_geral","processoportal/deliveryprocesses/gerente_geral_C74EE8E8.html"];
contentPage.processPage.elementUrls["_Igu8UnXyEeimL6JFnA2zmA"] = ["componentes_arte","processoportal/deliveryprocesses/componentes_arte_51F7D1B3.html"];
contentPage.processPage.elementUrls["_f1ACInX0EeimL6JFnA2zmA"] = ["produto_final","processoportal/deliveryprocesses/produto_final_D9E4EE82.html"];
contentPage.processPage.elementUrls["_f0jWNHX0EeimL6JFnA2zmA"] = ["gerente_arte","processoportal/deliveryprocesses/gerente_arte_D52967C1.html"];
contentPage.processPage.elementUrls["_V3BA8XXyEeimL6JFnA2zmA"] = ["Testes","processoportal/deliveryprocesses/Testes_7A5076D5.html"];
contentPage.processPage.elementUrls["_Ff4CIHXsEeimL6JFnA2zmA"] = ["gerente_portal","processoportal/deliveryprocesses/gerente_portal_6CD66661.html"];
contentPage.processPage.elementUrls["_HUu1gHXtEeimL6JFnA2zmA"] = ["estimar_prazo_desenvolvimento","processoportal/deliveryprocesses/estimar_prazo_desenvolvimento_60CA067E.html"];
contentPage.processPage.elementUrls["_AxdHAHXzEeimL6JFnA2zmA"] = ["funcionalidades_testadas","processoportal/deliveryprocesses/funcionalidades_7217F5BC.html"];
contentPage.processPage.elementUrls["_wy8IxnXaEeimL6JFnA2zmA"] = ["protocolo_aberto","processoportal/deliveryprocesses/protocolo_aberto_4AE0FAAA.html"];
contentPage.processPage.elementUrls["_FqL_QHXtEeimL6JFnA2zmA"] = ["idealizar_arte","processoportal/deliveryprocesses/idealizar_arte_ABA23829.html"];
contentPage.processPage.elementUrls["_KBRTgnfKEei1LJy4i5tyEQ"] = ["validar_requisitos","processoportal/deliveryprocesses/validar_requisitos_640B9A22.html"];
contentPage.processPage.elementUrls["_zajMwHXxEeimL6JFnA2zmA"] = ["componentes_arte","processoportal/deliveryprocesses/componentes_arte_794E4193.html"];
contentPage.processPage.elementUrls["_OzPmwHXzEeimL6JFnA2zmA"] = ["gerente_teste","processoportal/deliveryprocesses/gerente_teste_FE5B2973.html"];
contentPage.processPage.elementUrls["_ZuBGgXXYEeimL6JFnA2zmA"] = ["idealizador","processoportal/deliveryprocesses/idealizador_813032AA.html"];
contentPage.processPage.elementUrls["_GVQVgHXtEeimL6JFnA2zmA"] = ["listar_tarefas","processoportal/deliveryprocesses/listar_tarefas_DBB3CE9.html"];
contentPage.processPage.elementUrls["_eSDosXX0EeimL6JFnA2zmA"] = ["Corrigir e Atualizar ","processoportal/deliveryprocesses/Corrigir e Atualizar_6134244E.html"];
contentPage.processPage.elementUrls["_KBRTgXfKEei1LJy4i5tyEQ"] = ["idealizador","processoportal/deliveryprocesses/idealizador_7572860C.html"];
contentPage.processPage.elementUrls["_9I_ykXXyEeimL6JFnA2zmA"] = ["gerente_arte","processoportal/deliveryprocesses/gerente_arte_B5FA2310.html"];
contentPage.processPage.elementUrls["_X5jgcHXyEeimL6JFnA2zmA"] = ["testar_usabilidade","processoportal/deliveryprocesses/testar_usabilidade_5304F3B8.html"];
contentPage.processPage.elementUrls["_f0jWMHX0EeimL6JFnA2zmA"] = ["desenvolvedores_portal","processoportal/deliveryprocesses/desenvolvedores_portal_109785A2.html"];
contentPage.processPage.elementUrls["_XW1N4HXyEeimL6JFnA2zmA"] = ["testar_interacao","processoportal/deliveryprocesses/testar_interacao_3FE0C429.html"];
contentPage.processPage.elementUrls["_AxdHBnXzEeimL6JFnA2zmA"] = ["avaliacao_testes","processoportal/deliveryprocesses/avaliacao_testes_2FE0CC01.html"];
contentPage.processPage.elementUrls["_ZctDUXX0EeimL6JFnA2zmA"] = ["gerente_teste","processoportal/deliveryprocesses/gerente_teste_3CA5BE4C.html"];
contentPage.processPage.elementUrls["__LfdgXXsEeimL6JFnA2zmA"] = ["Planejar Projeto","processoportal/deliveryprocesses/Dialogar com Equipes_1CA588EF.html"];
contentPage.processPage.elementUrls["_KBRThnfKEei1LJy4i5tyEQ"] = ["especificao_requisitos_revisada","processoportal/deliveryprocesses/especificao_requisitos_revisada_289D7C41.html"];
contentPage.processPage.elementUrls["_-FBLYXXxEeimL6JFnA2zmA"] = ["Agregar Funcionalidades","processoportal/deliveryprocesses/d_B184BAFA.html"];
contentPage.processPage.elementUrls["_5QCdonXqEeimL6JFnA2zmA"] = ["gerente_geral","processoportal/deliveryprocesses/gerente_geral_FE02B7ED.html"];
contentPage.processPage.elementUrls["_IgSQYHXyEeimL6JFnA2zmA"] = ["agregar_artes_desenvolvimento","processoportal/deliveryprocesses/agregar_artes_desenvolvimento_BD2D7944.html"];
contentPage.processPage.elementUrls["_XnSZ0XX0EeimL6JFnA2zmA"] = ["Receber Portal","processoportal/deliveryprocesses/Receber Portal_21DEEB75.html"];
contentPage.processPage.elementUrls["_D5F1EHXtEeimL6JFnA2zmA"] = ["desenvolvedores_portal","processoportal/deliveryprocesses/desenvolvedores_portal_117E0853.html"];
contentPage.processPage.elementUrls["_W1mwIHXyEeimL6JFnA2zmA"] = ["equipe_teste","processoportal/deliveryprocesses/equipe_teste_34D60B1C.html"];
contentPage.processPage.elementUrls["_5QMOonXqEeimL6JFnA2zmA"] = ["especificacao_requisitos","processoportal/deliveryprocesses/especificacao_requisistos_2B5B12CE.html"];
contentPage.processPage.elementUrls["_qMlKsHXYEeimL6JFnA2zmA"] = ["idealizador","processoportal/deliveryprocesses/idealizador_2BD06C9.html"];
contentPage.processPage.elementUrls["_Ff4CInXsEeimL6JFnA2zmA"] = ["gerente_geral","processoportal/deliveryprocesses/gerente_geral_660D5A87.html"];
contentPage.processPage.elementUrls["_ZctDU3X0EeimL6JFnA2zmA"] = ["gerente_portal","processoportal/deliveryprocesses/gerente_portal_9418A827.html"];
contentPage.processPage.elementUrls["_wypN0HXaEeimL6JFnA2zmA"] = ["solicitar_portal","processoportal/deliveryprocesses/solicitar_portal_B85D3B59.html"];
contentPage.processPage.elementUrls["_5QMOoHXqEeimL6JFnA2zmA"] = ["resultado_analise","processoportal/deliveryprocesses/resultado_analise_32241EA8.html"];
contentPage.processPage.elementUrls["_nrQeoXXyEeimL6JFnA2zmA"] = ["Receber Sistema","processoportal/deliveryprocesses/Receber Sistema_EA4743DA.html"];
contentPage.processPage.elementUrls["_FpvTUHXtEeimL6JFnA2zmA"] = ["dividir_tarefas_arte","processoportal/deliveryprocesses/dividir_tarefas_arte_DB8BC36F.html"];
contentPage.processPage.elementUrls["_8U9jAXXxEeimL6JFnA2zmA"] = ["Agregacao","processoportal/deliveryprocesses/Agregacao_BDD3DABD.html"];
contentPage.processPage.elementUrls["_qC8uwXXyEeimL6JFnA2zmA"] = ["Resultados Testes","processoportal/deliveryprocesses/Resultados Tetes_8E2A9EC9.html"];
contentPage.processPage.elementUrls["_qxiR4nXYEeimL6JFnA2zmA"] = ["forma_resolucao","processoportal/deliveryprocesses/forma_resolucao_A281BB23.html"];
contentPage.processPage.elementUrls["_Ff4CJHXsEeimL6JFnA2zmA"] = ["gerente_arte","processoportal/deliveryprocesses/gerente_arte_31684880.html"];
contentPage.processPage.elementUrls["_DWhhQHXyEeimL6JFnA2zmA"] = ["agregar_funcionalidades","processoportal/deliveryprocesses/agregar_funcionalidades_A907C943.html"];
contentPage.processPage.elementUrls["_ZuBGg3XYEeimL6JFnA2zmA"] = ["necessidade_portal","processoportal/deliveryprocesses/necessidade_portal_D8A31C85.html"];
contentPage.processPage.elementUrls["_OzPmwnXzEeimL6JFnA2zmA"] = ["avaliacao_testes","processoportal/deliveryprocesses/avaliacao_testes_F7921D99.html"];
contentPage.processPage.elementUrls["_NG4oEnXyEeimL6JFnA2zmA"] = ["gerente_portal","processoportal/deliveryprocesses/gerente_portal_75DB3716.html"];
contentPage.processPage.elementUrls["_9I_yk3XyEeimL6JFnA2zmA"] = ["sistema_validado","processoportal/deliveryprocesses/sistema_validado_D6D0CEB.html"];
contentPage.processPage.elementUrls["_X80McXXJEeimL6JFnA2zmA"] = ["processoPortalDiagrama","processoportal/deliveryprocesses/processoPortalDiagrama_A62CB33C.html"];
contentPage.processPage.elementUrls["_PLp8MXXyEeimL6JFnA2zmA"] = ["Teste","processoportal/deliveryprocesses/Teste_122CB288.html"];
contentPage.processPage.elementUrls["_KBRThHfKEei1LJy4i5tyEQ"] = ["gerente_geral","processoportal/deliveryprocesses/gerente_geral_2F66881B.html"];
contentPage.processPage.elementUrls["_XXbq0HXyEeimL6JFnA2zmA"] = ["interacao","processoportal/deliveryprocesses/interacao_AE7796C0.html"];
contentPage.processPage.elementUrls["_XeX_IXXYEeimL6JFnA2zmA"] = ["Idealizar","processoportal/deliveryprocesses/Idealizar_D15E7BFC.html"];
contentPage.processPage.elementUrls["_PfakgXXYEeimL6JFnA2zmA"] = ["Projeto","processoportal/deliveryprocesses/Projeto_7B8F3A8A.html"];
contentPage.processPage.elementUrls["_FgBzInXsEeimL6JFnA2zmA"] = ["compreensao_portal","processoportal/deliveryprocesses/compreensao_portal_4D1B09B1.html"];
contentPage.processPage.elementUrls["_GsUnIHXsEeimL6JFnA2zmA"] = ["montar_prototipo","processoportal/deliveryprocesses/montar_prototipo_FE9BA637.html"];
contentPage.processPage.elementUrls["_X6JWUHXyEeimL6JFnA2zmA"] = ["usabilidade","processoportal/deliveryprocesses/usabilidade_D0C2A397.html"];
contentPage.processPage.elementUrls["_W15rEnXyEeimL6JFnA2zmA"] = ["funcionalidades_testadas","processoportal/deliveryprocesses/funcionalidades_6C0AA939.html"];
contentPage.processPage.elementUrls["_GVQVgnXtEeimL6JFnA2zmA"] = ["tarefas_divididas","processoportal/deliveryprocesses/tarefas_divididas_6F2310F.html"];
contentPage.processPage.elementUrls["_Igu8UHXyEeimL6JFnA2zmA"] = ["desenvolvedores_portal","processoportal/deliveryprocesses/desenvolvedores_portal_58C0DD8D.html"];
contentPage.processPage.elementUrls["_kAZL4HXxEeimL6JFnA2zmA"] = ["desenvolver_funcionalidades","processoportal/deliveryprocesses/desenvolver_funcionalidades_4A63AC54.html"];
contentPage.processPage.elementUrls["_zaQR0HXxEeimL6JFnA2zmA"] = ["criar_artes","processoportal/deliveryprocesses/criar_artes_5A5E8478.html"];
contentPage.processPage.elementUrls["_Ff4CKHXsEeimL6JFnA2zmA"] = ["devops","processoportal/deliveryprocesses/devops_F5FA2A9F.html"];
contentPage.processPage.elementUrls["_MjauoHXyEeimL6JFnA2zmA"] = ["avaliar_agregacao","processoportal/deliveryprocesses/avaliar_agregacao_78682B43.html"];
contentPage.processPage.elementUrls["_GIs8sHXsEeimL6JFnA2zmA"] = ["apresentar_requisitos","processoportal/deliveryprocesses/apresentar_requisitos_F078F88F.html"];
